services:
  - type: web
    name: chonect-backend
    env: java
    # Usar imagen de Docker Hub en lugar de construir
    imageUrl: carrlox/chonect-backend:latest
    port: 8080
    healthCheckPath: /actuator/health
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        generateValue: true
      - key: SPRING_DATASOURCE_USERNAME
        generateValue: true
      - key: SPRING_DATASOURCE_PASSWORD
        generateValue: true
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.MySQLDialect
      # Variables para correo (Resend API)
      - key: RESEND_API_KEY
        value: re_Sv3QiaGU_3GqxUm32zVA4W1M97TJSrgUe
