scalar JSON

type UserConfig {
  themes: JSON
  plan: String
  planExpirationDate: String
}

type Folder {
  id: ID!
  name: String!
  projects: [Project]
}

type Project {
  id: ID!
  projectName: String!
  description: String
  folderId: ID
  folder: Folder
  pages: [Page]
  user: User
}

type User {
  id: ID!
  firstName: String
  lastName: String
  username: String
  email: String
  numberOfProjects: Int
  recentProjectIds: [String]
  config: UserConfig
  folders: [Folder]
}

type Page {
  id: ID!
  pageName: String!
  config: PageConfig
  canvas: Canvas
}

type PageConfig {
  grid: String
  backgroundColor: String
  resolution: String
}

type Canvas {
  id: ID
  elements: [Element]
  connections: [Connection]
}

type Element {
  id: ID!
  elementId: String!
  type: String!
  positionX: String!
  positionY: String!
  x: String! # Alias para positionX
  y: String! # Alias para positionY
  styles: JSON # Changed to JSON
  layer: ElementLayer
}

type ElementLayer {
  locked: Boolean
  zIndex: Int
  visible: Boolean
}

type Connection {
  id: ID!
  fromElementId: String!
  toElementId: String!
  actionType: String!
  orderNum: Int
  delay: Int
  isParallel: Boolean
}

input ProjectInput {
  projectName: String!
  description: String
  folderId: ID # Optional folder assignment
  pages: [PageInput]
}

input PageInput {
  id: ID
  pageName: String!
  config: PageConfigInput
  canvas: CanvasInput
}

input PageConfigInput {
  grid: String
  backgroundColor: String
  resolution: String
}

input CanvasInput {
  elements: [ElementInput]
  connections: [ConnectionInput]
}

input ElementInput {
  elementId: String!
  type: String!
  positionX: String!
  positionY: String!
  styles: JSON # Changed to JSON
  layer: ElementLayerInput
}

input ElementLayerInput {
  locked: Boolean
  zIndex: Int
  visible: Boolean
}

input ConnectionInput {
  fromElementId: String!
  toElementId: String!
  actionType: String!
  orderNum: Int
  delay: Int
  isParallel: Boolean
}

type Query {
  findProjectById(id: ID!): Project
  findAllProjects: [Project]
  getUserConfig: UserConfig
  getFolders: [Folder]
}

type Mutation {
  createProject(projectInput: ProjectInput!): Project
  updateProject(projectId: ID!, projectInput: ProjectInput!): Project
  updateElementPosition(
    elementId: String!
    positionX: String!
    positionY: String!
  ): Element
  updateElementStyles(elementId: String!, styles: JSON!): Element
  updateElement(elementId: String!, elementInput: ElementInput!): Element

  # Folder management
  createFolder(name: String!): Folder
}
